# Main variables for SMTP Master

# Database connection details
master_db_host: localhost
master_db_name: master_postfix
master_db_user: "{{ master_db_user }}"
master_db_password: "{{ vault_db_root_password }}"

# Slave database connection details
slave_db_user: mail_sync
slave_db_password: "{{ vault_slave_db_password }}"

# SMTP Node repository
smtp_node_repo: https://github.com/CristiBulat/SMTP_Node.git
smtp_node_version: main

# Default SMTP configuration
default_message_size_limit: 52428800
default_maximal_queue_lifetime: 1d
default_bounce_queue_lifetime: 1d
default_dkim_selector: mail